[pytest]
# Indica a pytest dónde están tus archivos de prueba
testpaths = tests

# Configuración de ejecución y reporte HTML
# -v: Modo detallado
# -s: Muestra tus prints en la consola
# --html: Crea el reporte con el nombre que elijas
# --self-contained-html: Hace que el reporte sea un único archivo fácil de compartir
addopts = -v -s --html=reporte_final.html --self-contained-html

# Reglas para que Pytest reconozca tus archivos y clases
python_files = test_*.py
python_classes = Test*
python_functions = test_*